repos:
  - repo: https://github.com/tmasthay/GitHookEm
    rev: main
    hooks:
      - id: commit-msg-directive
      - id: ban-super-secret

  - repo: https://github.com/psf/black
    rev: stable  # Replace with the specific version you want to pin
    hooks:
      - id: black
        args: [--line-length=80, --skip-string-normalization, --experimental-string-processing]
