- id: commit-msg-directive
  name: Commit Message Directive Hook
  entry: python git_hook_em/commit_msg_validator/commit_msg_validator.py
  language: python
  stages: [commit-msg]

- id: ban-super-secret
  name: Ban Super Secret
  entry: python git_hook_em/pre_commit_validator/ban_souper_secret.py
  language: python
  stages: [pre-commit]
