- id: hello-world-commit-msg
  name: Hello World Commit Message Hook
  entry: python git_hook_em/hello.py
  language: python
  stages: [commit-msg]

- id: real-commit-msg
  name: Real Commit Message Hook
  entry: python git_hook_em/commit_msg_validator/commit_msg_validator.py
  language: python
  stages: [commit-msg]
