-   id: commit-msg-directives
    name: Commit Message Directive Hook
    entry: commit-msg-directives
    language: script
    types: [text]
-   id: ban-super-secret
    name: Ban Super Secret
    entry: ban-super-secret
    language: script
    types: [text]
