-   id: commit-msg-directive
    name: Commit Message Directive Hook
    entry: commit-msg-directive
    language: system
    stages: [commit-msg]

-   id: ban-super-secret
    name: Ban Super Secret
    entry: ban-super-secret
    language: system
    stages: [pre-commit]
